# Init pose (x = -6.5, y = 0.0)
INIT_X: -3.5
INIT_Y: 0.0
INIT_Z: 0.0
INIT_ROLL: 0.0
INIT_PITCH: 0.0
INIT_YAW: 3.00

# Parameters (0.001 < imu < ?, 0.03 < odom < ?)
INIT_SIGMA: 0.0001
SIGMA_IMU: 0.001
SIGMA_ODOM: 0.01
SIGMA_NDT: 0.001

#MOTION_NOISE_NN: 0.01
#MOTION_NOISE_NO: 0.001
#MOTION_NOISE_ON: 0.0001
#MOTION_NOISE_OO: 0.0001