# Init pose
INIT_X: 0.0
INIT_Y: 0.0
INIT_Z: 0.0
INIT_ROLL: 0.0
INIT_PITCH: 0.0
INIT_YAW: 2.6

# Parameters
INIT_SIGMA: 0.00001
SIGMA_IMU: 0.001
SIGMA_ODOM: 0.001
SIGMA_NDT: 0.01

#MOTION_NOISE_NN: 0.01
#MOTION_NOISE_NO: 0.001
#MOTION_NOISE_ON: 0.0001
#MOTION_NOISE_OO: 0.0001