# Downsampling Parameter (0.30?)
VOXEL_SIZE: 0.3

# Paththrough Parameter (60.0)
LIMIT_RANGE: 60.0


# Matching Parameters
TRANS_EPSILON: 0.001
STEP_SIZE: 0.1
RESOLUTION: 5.0
MAX_ITERATION: 35

# Matching Score
MATCHING_SCORE_TH: 2.7

# Map Offset (x = 515.480289, y = -267.639866)
MAP_OFFSET_X: 8.78
MAP_OFFSET_Y: 1.0
MAP_OFFSET_Z: 0.0
MAP_OFFSET_ROLL: 0.0
MAP_OFFSET_PITCH: 0.0
MAP_OFFSET_YAW: -3.14